# Generated by Django 5.1.4 on 2024-12-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_doctor_image_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dep_name',
        ),
    ]
